name: CI Tests

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - develop
      - release/*

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Display Info
        run: |
          echo "ФИО: Иванов Иван Иванович"
          echo "Группа: ИУ6-42Б"
          echo "Github Nickname: ${{ github.actor }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: python -m unittest discover -s /home/runner/work/geometric_lib/geometric_lib/tests

      - name: Run Linter
        run: flake8 .
